name: "Pytest HTML Plus Action"
description: "Run pytest with pytest-html-plus and generate rich reports"
inputs:
  pytest-args:
    description: "Arguments to pass directly to pytest (e.g. 'tests/ --rerun=1')"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile"
